# Generated by Django 4.0.2 on 2022-02-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_rename_img_resumedetial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedetial',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
