# Generated by Django 4.0.2 on 2022-02-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_resumedetial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetial',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectdetial',
            name='project_image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='projectdetial',
            name='project_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectdetial',
            name='project_slug',
            field=models.SlugField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projectdetial',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
