# Generated by Django 4.0.2 on 2022-02-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_projectdetial_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdetial',
            old_name='project_slug',
            new_name='slug',
        ),
    ]
